### ISSUE TITLE
Store data in SQLite (so that process memory usage does not increase)

### ISSUE THREAD

**Issue by guettli** [sachaos/viddy#104]
If you run viddy for several hours the process eats up all memory.

A SQLite based storage would be great, so that memory consumption does not grow.

An the sqlite file could be shared to other people so that they can have a look at the history, too.

Related: #103

**Comment by sachaos** [comment]
I've implemented feature to save and load history in viddy v1.0.0-rc.2.
We have been storing results in memory until now, but since we switched to using SQLite, we expect a significant reduction in memory usage. If you encounter any bugs or issues, please let us know.

https://github.com/sachaos/viddy/issues/117#issuecomment-2294818886

**Comment by sachaos** [comment]
Viddy v1.0.0 is available now.
